channel_sources:
  - nsls2forge,defaults
channel_targets:
  - nsls2forge main
docker_image:
  - nsls2/nsls2forge:latest
cuda_compiler_version:
  - None
cairo:
  - 1.14
glib:
  - 2.63
python:
  - 3.6
  - 3.7
  - 3.8
