{% set name = "pygobject" %}
{% set version = "3.40.0" %}
{% set majmin = '.'.join(version.split('.', 2)[:2]) %}
{% set sha256 = "67d61fac9f5aa83bf2edccbc286802ce0f1c3dde8f83103b7c765b91a6ed905f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/{{ name }}/{{ majmin }}/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<35]

requirements:
  build:
    - {{ compiler('c') }}
    - meson
    - ninja
    - pkg-config
  host:
    - python
    - glib
    - gobject-introspection
    - libffi
    - pycairo
  run:
    - python
    - glib
    - gobject-introspection
    - libffi
    - libiconv  # on Windows we seem to need the conda-forge version here (see #15)
    - pycairo

test:
  requires:
    - gtk3
    - pkg-config
  imports:
    - gi
    - gi.repository.GLib
    - gi.repository.Gtk
  commands:
    # verify that header gets installed and can be located through pkg-config
    {% set pc = "pygobject-3.0" %}
    {% set header = "pygobject.h" %}
    - test -f $PREFIX/include/{{ pc }}/{{ header }}  # [unix]
    - test -f `pkg-config --variable=pygobjectincludedir --dont-define-prefix {{ pc }}`/{{ header }}  # [unix]
    - if not exist %LIBRARY_INC%\\{{ pc }}\\{{ header }} exit 1  # [win]
    - for /f "usebackq tokens=*" %%a in (`pkg-config --variable=pygobjectincludedir --dont-define-prefix {{ pc }}`) do if not exist "%%a/{{ header }}" exit 1  # [win]


about:
  home: https://pygobject.readthedocs.io
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: 'Python bindings for GObject Introspection'

  description: |
    PyGObject is a Python package which provides bindings for GObject based libraries
    such as GTK+, GStreamer, WebKitGTK+, GLib, GIO and many more.

  doc_url: https://pygobject.readthedocs.io
  dev_url: https://git.gnome.org/browse/pygobject
