{% set name = "pygobject" %}
{% set version = "3.32.2" %}
{% set majmin = '.'.join(version.split('.', 2)[:2]) %}
{% set sha256 = "c39ca2a28364b57fa00549c6e836346031e6b886c3ceabfd8ab4b4fed0a83611" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://ftp.gnome.org/pub/GNOME/sources/{{ name }}/{{ majmin }}/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<36 or not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cairo
    - glib
    - gobject-introspection
    - libffi
    - pep517
    - pycairo
    - pytest
  run:
    - python
    - {{ pin_compatible('cairo') }}
    - {{ pin_compatible('pycairo') }}
    - glib
    - gobject-introspection
    - libffi

test:
  imports:
    - gi

about:
  home: http://www.gtk.org
  license: LGPL
  license_file: COPYING
  summary: Access to GObject-based libraries in Python.
