{% set name = "pygobject" %}
{% set version = "3.30.5" %}
{% set majmin = '.'.join(version.split('.', 2)[:2]) %}
{% set sha256 = "9deeac63e0d834646221cf37404d2fdfb3eac6d49aa50133ef9ac38f09ff2bfd" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://ftp.gnome.org/pub/GNOME/sources/pygobject/{{ majmin }}/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    - macos-tests.patch
    - meson-rpaths.patch  # [linux]

build:
  number: 0
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - glib <=2.56
    - gobject-introspection 1.*
    - libffi
    - m2-msys2-runtime  # [win]
    - meson
    - ninja
    - pycairo
    - python
    - {{posix}}patch
    - {{native}}pkg-config
  host:
    - python
    - flake8  # for testing during the build
    - pytest
  run:
    - python
    - glib <=2.56
    - gobject-introspection 1.*
    - libffi
    - libiconv  # on Windows we seem to need the conda-forge version here (see #15)
    - pycairo

test:
  imports:
    - gi
    - gi.repository.GLib
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://pygobject.readthedocs.io
  license: LGPL-2.1
  license_family: LGPL
  license_file: COPYING
  summary: Python bindings for GObject Introspection
  description: |
    PyGObject is a Python package which provides bindings for GObject based libraries
    such as GTK+, GStreamer, WebKitGTK+, GLib, GIO and many more.
  doc_url: https://pygobject.readthedocs.io
  dev_url: https://git.gnome.org/browse/pygobject
